version: "3.9"
services:
   db:
     image: mysql:8.0.30
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: dbmywebapp
       MYSQL_USER: testuser
       MYSQL_PASSWORD: password
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0
    ports:
      - '9090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat:10.1.0-jdk17
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '6025:8080'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbmywebapp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
volumes:
    db_vol:    
