global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['10.235.2.100:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['10.235.2.100:9100']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['10.235.2.100:8080']